### ISSUE TITLE
Upload video issue

### ISSUE THREAD

**Issue by anthonymq** [dfinity/cancan#5]
Hi,
Thanks for the great work. I encountered an error while trying to upload a video via the frontend canister deployed on my local node.
I've tested with the UI on the development server and it's works great.

**Comment by y-ang2010** [comment]
![image](https://user-images.githubusercontent.com/12936750/117428678-dde9c500-af58-11eb-8e7d-152987e74ecc.png)

I get same question , upload video failed .

Video Size : 32Mb
Video file format : mp4

**Comment by anthonymq** [comment]
Okay I think I identified the problem on the local node deployment : 
`
Storing video thumbnail...
video.ts:131 Unable to store video thumbnail: TypeError: Cannot convert a BigInt value to a number
`
Works on the devserver.

**Comment by lebinh199** [comment]
Hope solve this soon

**Comment by codelemur** [comment]
Hey @anthonymq  we've got a bug where the compiler sometimes doesn't correctly process some code in one of our dependencies.

It doesn't turn `BigInt(2)**BigInt(n+1)` into `Math.pow(2,n+1)`, but instead tries to do `Math.pow(BigInt)` which results in the error you're seeing above..

That change has to happen in a dependency (@dfinity/agent), and we'll update this issue as soon as we've got that part working!

**Comment by msecret** [comment]
@anthonymq  I just pushed a PR for a fix for the BigInt error:  https://github.com/dfinity/cancan/pull/6. We were compiling our javascript to an unsupported version for one of our dependencies. Feel free to pull that branch down to see if it fixes the issue for you.

We're still looking at another issue with video upload from the canister frontend, you can track that here: https://github.com/dfinity/cancan/issues/7.

**Comment by flyq** [comment]
> Feel free to pull that branch down to see if it fixes the issue for you.
the problem is still here:
![image](https://user-images.githubusercontent.com/16486808/117531440-0cc57100-b015-11eb-8777-03865012f78a.png)

![image](https://user-images.githubusercontent.com/16486808/117531531-6d54ae00-b015-11eb-8861-caced1b16c73.png)

### env
dfx 0.7.0-beta.6

node v15.12.0

browser chrome

**Comment by msecret** [comment]
I just created https://github.com/dfinity/cancan/pull/11, turns out we had to be even more prescriptive about our browserlist as I believe one of the rules was including an older samsung browser version. Be sure to delete the `node_modules/.cache` directory as otherwise new browserlist rules might not update in the build. This along with https://github.com/dfinity/cancan/pull/8 should get video upload working again, but please update if you run into any problems.

**Comment by taylorham** [comment]
Closed by #11
